Repository Activiti/activiti-cloud-full-chart, pull requests merged in 2022-12, with the labels that each got.

#1004 Update docker image tags to 7.7.0-alpha.19
  charts/activiti-cloud-full-example/README.md
  charts/activiti-cloud-full-example/values.yaml
Labels: updatebot

#1005 Update docker image tags to 7.7.0-alpha.20
  charts/activiti-cloud-full-example/README.md
  charts/activiti-cloud-full-example/values.yaml
Labels: updatebot

#1007 chore(deps): upgrade Activiti/activiti-cloud-common-chart to version 7.7.0-alpha.17
  charts/activiti-cloud-full-example/README.md
  charts/activiti-cloud-full-example/requirements.yaml
Labels: updatebot, develop

#1008 chore(deps): upgrade Activiti/activiti-cloud-common-chart to version 7.7.0-alpha.18
  charts/activiti-cloud-full-example/README.md
  charts/activiti-cloud-full-example/requirements.yaml
Labels: updatebot, develop

#1009 Update docker image tags to 7.7.0-alpha.21
  charts/activiti-cloud-full-example/README.md
  charts/activiti-cloud-full-example/values.yaml
Labels: updatebot

#1017 Update docker image tags to 7.7.0-alpha.22
  charts/activiti-cloud-full-example/README.md
  charts/activiti-cloud-full-example/values.yaml
Labels: updatebot

#1019 Update docker image tags to 7.8.0-alpha.1
  charts/activiti-cloud-full-example/README.md
  charts/activiti-cloud-full-example/values.yaml
Labels: updatebot

#1021 Update docker image tags to 7.8.0-alpha.2
  charts/activiti-cloud-full-example/README.md
  charts/activiti-cloud-full-example/values.yaml
Labels: updatebot

#1023 Update docker image tags to 7.8.0-alpha.3
  charts/activiti-cloud-full-example/README.md
  charts/activiti-cloud-full-example/values.yaml
Labels: updatebot

#1027 Update docker image tags to 7.8.0-alpha.4
  charts/activiti-cloud-full-example/README.md
  charts/activiti-cloud-full-example/values.yaml
Labels: updatebot

#1024 AAE-11894 Remove create prerelease step for rc tag workflow
  .github/workflows/rc.yml
Labels: enhancement
