Repository Activiti/activiti-cloud-full-chart, pull requests merged in 2023-01, with the labels that each got.

#1026 chore(deps): upgrade Activiti/activiti-cloud-common-chart to version 7.8.0-alpha.2
  charts/activiti-cloud-full-example/README.md
  charts/activiti-cloud-full-example/requirements.yaml
Labels: updatebot, develop

#1031 Promote activiti-cloud-full-chart alpha versions to alfresco-process-releases
  .github/workflows/main.yml
  .jx/updatebot.yaml
Labels: enhancement

#1035 Update docker image tags to 7.8.0-alpha.7
  charts/activiti-cloud-full-example/README.md
  charts/activiti-cloud-full-example/values.yaml
Labels: updatebot

#1036 Update docker image tags to 7.8.0-alpha.8
  charts/activiti-cloud-full-example/README.md
  charts/activiti-cloud-full-example/values.yaml
Labels: updatebot

#1037 Update docker image tags to 7.8.0-alpha.9
  charts/activiti-cloud-full-example/README.md
  charts/activiti-cloud-full-example/values.yaml
Labels: updatebot

#1038 Update docker image tags to 7.8.0-alpha.10
  charts/activiti-cloud-full-example/README.md
  charts/activiti-cloud-full-example/values.yaml
Labels: updatebot

#1040 Update docker image tags to 7.8.0-alpha.11
  charts/activiti-cloud-full-example/README.md
  charts/activiti-cloud-full-example/values.yaml
Labels: updatebot

#1041 Update docker image tags to 7.8.0-alpha.12
  charts/activiti-cloud-full-example/README.md
  charts/activiti-cloud-full-example/values.yaml
Labels: updatebot

#1043 Update docker image tags to 7.8.0-alpha.14
  charts/activiti-cloud-full-example/README.md
  charts/activiti-cloud-full-example/values.yaml
Labels: updatebot

#1044 Update docker image tags to 7.8.0-alpha.15
  charts/activiti-cloud-full-example/README.md
  charts/activiti-cloud-full-example/values.yaml
Labels: updatebot

#1047 Update docker image tags to 7.9.0-alpha.1
  charts/activiti-cloud-full-example/README.md
  charts/activiti-cloud-full-example/values.yaml
Labels: updatebot

#1049 Update docker image tags to 7.9.0-alpha.3
  charts/activiti-cloud-full-example/README.md
  charts/activiti-cloud-full-example/values.yaml
Labels: updatebot

#1050 Update docker image tags to 7.9.0-alpha.4
  charts/activiti-cloud-full-example/README.md
  charts/activiti-cloud-full-example/values.yaml
Labels: updatebot

#1051 Update docker image tags to 7.9.0-alpha.5
  charts/activiti-cloud-full-example/README.md
  charts/activiti-cloud-full-example/values.yaml
Labels: updatebot

#1052 Update docker image tags to 7.9.0-alpha.6
  charts/activiti-cloud-full-example/README.md
  charts/activiti-cloud-full-example/values.yaml
Labels: updatebot

#1053 Update docker image tags to 7.9.0-alpha.7
  charts/activiti-cloud-full-example/README.md
  charts/activiti-cloud-full-example/values.yaml
Labels: updatebot
