Repository Activiti/activiti-cloud-full-chart, pull requests merged in 2024-10, with the labels that each got.

#1463 Update docker image tags to 8.7.0-alpha.42
  charts/activiti-cloud-full-example/README.md
  charts/activiti-cloud-full-example/values.yaml
Labels: updatebot

#1464 Update docker image tags to 8.7.0-alpha.43
  charts/activiti-cloud-full-example/README.md
  charts/activiti-cloud-full-example/values.yaml
Labels: updatebot

#1466 Update docker image tags to 8.7.0-alpha.44
  charts/activiti-cloud-full-example/README.md
  charts/activiti-cloud-full-example/values.yaml
Labels: updatebot

#1467 Update docker image tags to 8.7.0-alpha.45
  charts/activiti-cloud-full-example/README.md
  charts/activiti-cloud-full-example/values.yaml
Labels: updatebot

#1469 Update docker image tags to 8.7.0-alpha.46
  charts/activiti-cloud-full-example/README.md
  charts/activiti-cloud-full-example/values.yaml
Labels: updatebot

#1470 Update docker image tags to 8.7.0-alpha.47
  charts/activiti-cloud-full-example/README.md
  charts/activiti-cloud-full-example/values.yaml
Labels: updatebot

#1473 Update docker image tags to 8.7.0-alpha.49
  charts/activiti-cloud-full-example/README.md
  charts/activiti-cloud-full-example/values.yaml
Labels: updatebot

#1475 Update docker image tags to 8.7.0-alpha.50
  charts/activiti-cloud-full-example/README.md
  charts/activiti-cloud-full-example/values.yaml
Labels: updatebot

#1476 Update docker image tags to 8.7.0-alpha.51
  charts/activiti-cloud-full-example/README.md
  charts/activiti-cloud-full-example/values.yaml
Labels: updatebot

#1477 Update docker image tags to 8.7.0-alpha.52
  charts/activiti-cloud-full-example/README.md
  charts/activiti-cloud-full-example/values.yaml
Labels: updatebot

#1478 Update docker image tags to 8.7.0-alpha.53
  charts/activiti-cloud-full-example/README.md
  charts/activiti-cloud-full-example/values.yaml
Labels: updatebot

#1481 chore(deps): upgrade Activiti/activiti-cloud-common-chart to version 8.7.0-alpha.2
  charts/activiti-cloud-full-example/README.md
  charts/activiti-cloud-full-example/requirements.yaml
Labels: updatebot, develop

#1479 AAE-26793 Add Consumer deployment with PDB values
  charts/activiti-cloud-full-example/README.md
  charts/activiti-cloud-full-example/pdb-values.yaml
  charts/activiti-cloud-full-example/requirements.yaml
  charts/activiti-cloud-full-example/values.yaml
Labels: enhancement

#1482 AAE-26793 Fix Makefile for Consumer deployment Docker image update
  charts/activiti-cloud-full-example/Makefile
Labels: bug

#1484 Update docker image tags to 8.7.0-alpha.55
  charts/activiti-cloud-full-example/README.md
  charts/activiti-cloud-full-example/values.yaml
Labels: updatebot

#1485 Update docker image tags to 8.7.0-alpha.56
  charts/activiti-cloud-full-example/README.md
  charts/activiti-cloud-full-example/values.yaml
Labels: updatebot

#1488 Update docker image tags to 8.7.0-alpha.57
  charts/activiti-cloud-full-example/README.md
  charts/activiti-cloud-full-example/values.yaml
Labels: updatebot

#1489 Update docker image tags to 8.7.0-alpha.58
  charts/activiti-cloud-full-example/README.md
  charts/activiti-cloud-full-example/values.yaml
Labels: updatebot

#1492 Update docker image tags to 8.7.0-alpha.59
  charts/activiti-cloud-full-example/README.md
  charts/activiti-cloud-full-example/values.yaml
Labels: updatebot

#1493 Update docker image tags to 8.7.0-alpha.60
  charts/activiti-cloud-full-example/README.md
  charts/activiti-cloud-full-example/values.yaml
Labels: updatebot
