Repository Activiti/activiti-cloud-full-chart, pull requests merged in 2025-10, with the labels that each got.

#1731 chore(deps): upgrade Activiti/activiti-cloud-common-chart to version 8.8.0-alpha.13
  charts/activiti-cloud-full-example/README.md
  charts/activiti-cloud-full-example/requirements.yaml
Labels: updatebot, develop

#1736 AAE-38600 Move Zookeeper to bitnamilegacy repository
  charts/activiti-cloud-full-example/README.md
  charts/activiti-cloud-full-example/values.yaml
Labels: bug

#1738 Update docker image tags to 8.8.0-alpha.116
  charts/activiti-cloud-full-example/README.md
  charts/activiti-cloud-full-example/values.yaml
Labels: updatebot

#1740 Update docker image tags to 8.8.0-alpha.117
  charts/activiti-cloud-full-example/README.md
  charts/activiti-cloud-full-example/values.yaml
Labels: updatebot
